import markdown
import os
from datetime import datetime

def save_as_html(md_text, task_name="Strategic_Report"):
    
    """Markdown raporunu şık bir HTML dosyasına dönüştürür."""
    html_content = markdown.markdown(md_text, extensions=['tables', 'fenced_code'])
    
    styled_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 20px; background-color: #f4f7f6; }}
            h1, h2, h3 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 0 20px rgba(0,0,0,0.1); }}
            th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #3498db; color: white; }}
            tr:hover {{ background-color: #f5f5f5; }}
            .footer {{ margin-top: 30px; font-size: 0.8em; color: #7f8c8d; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>🚀 {task_name.replace('_', ' ')}</h1>
        {html_content}
        <div class="footer">Generated by BeeAI Strategy Agent | {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
    </body>
    </html>
    """
    
    filename = f"reports/{task_name}_{datetime.now().strftime('%Y%m%d_%f')}.html"
    os.makedirs('reports', exist_ok=True)
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(styled_html)
    
    return filename