"""HTML report generation utilities for BeeAI strategy analysis pipeline.

This module provides functions to convert Markdown-formatted analysis results
into styled HTML reports for easy viewing and sharing.
"""

import os
from datetime import datetime
from typing import Optional
import html

import markdown

from src.config.settings import REPORTS_DIR

# HTML template for styled report generation
_HTML_TEMPLATE: str = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            background-color: #f4f7f6;
        }}
        h1, h2, h3 {{
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }}
        th, td {{
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .footer {{
            margin-top: 30px;
            font-size: 0.8em;
            color: #7f8c8d;
            text-align: center;
        }}
    </style>
</head>
<body>
    <h1>🚀 {title}</h1>
    {content}
    <div class="footer">Generated by BeeAI Strategy Agent | {timestamp}</div>
</body>
</html>
"""


def _ensure_reports_directory() -> None:
    """Create reports directory if it does not exist.
    
    Ensures the output directory is available before writing HTML files.
    Uses os.makedirs with exist_ok=True for thread-safe creation.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)


def save_as_html(
    md_text: str,
    task_name: str = "Strategic_Report"
) -> str:
    """Convert Markdown text to a styled HTML report file.
    
    Parses Markdown input with support for tables and code blocks, wraps
    it in a professional HTML template with inline CSS styling, and writes
    to the reports directory.
    
    Args:
        md_text: Markdown-formatted text to convert.
        task_name: Human-readable report name (underscores replaced with spaces).
                   Used for both the HTML title and filename.
    
    Returns:
        Full filepath to the generated HTML report.
    
    Raises:
        IOError: If the report file cannot be written.
    """
    _ensure_reports_directory()
    
    # Convert Markdown to HTML with support for tables and code blocks
    html_content: str = markdown.markdown(
        md_text,
        extensions=['tables', 'fenced_code']
    )
    
    # Format title for display (replace underscores with spaces)
    display_title: str = task_name.replace('_', ' ')
    current_timestamp: str = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    # Populate HTML template with content
    styled_html: str = _HTML_TEMPLATE.format(
        title=display_title,
        content=html_content,
        timestamp=current_timestamp
    )
    
    # Write HTML to file
    filename: str = f"{REPORTS_DIR}/{task_name}.html"
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(styled_html)
    except IOError as e:
        raise IOError(f"Failed to write report to {filename}: {e}") from e
    
    return filename


def render_html_from_pipeline_output(output, name: str, language: str = "tr") -> str:
    """Render a minimal HTML email body from PipelineOutput, converting markdown to HTML.
    Supports Turkish and English email/report bodies.
    """
    safe_name = html.escape(name)
    strategic_html = markdown.markdown(output.strategic_report, extensions=['tables', 'fenced_code'])
    review_html = markdown.markdown(output.review_analysis, extensions=['tables', 'fenced_code'])
    if language == "tr":
        html_body = f"""
        <html><body>
        <h2>Merhaba {safe_name},</h2>
        <p>Günün strateji raporunuz aşağıdadır:</p>
        {strategic_html}
        {review_html}
        <br><p>Saygılarımızla,<br>BeeAI Haber Ajansı</p>
        </body></html>
        """
    else:
        html_body = f"""
        <html><body>
        <h2>Hi {safe_name},</h2>
        <p>Here is your daily strategy report:</p>
        {strategic_html}
        {review_html}
        <br><p>Best regards,<br>BeeAI News Agent</p>
        </body></html>
        """
    return html_body